name: farmpedia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  geolocator: ^8.0.0
  uuid: ^4.4.0
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.0.20
  youtube_player_flutter: ^8.0.0
  webview_flutter: ^3.0.4
  intl: ^0.17.0
  http: ^0.13.3
  audioplayers: ^6.0.0
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSans-Bold.ttf
        - asset: assets/fonts/GmarketSans-Light.ttf
        - asset: assets/fonts/GmarketSans-Medium.ttf
        - asset: assets/video/sky.mp4
